# Generated by Django 3.1.7 on 2021-03-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my.google', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Google',
            new_name='GoogleLogin',
        ),
    ]
